version: "3.9"

networks:
  default:
    name: kong-net

services:
  kong:
    image: kong:2.5.0-alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yml"
      KONG_STREAM_LISTEN: "0.0.0.0:9999 udp"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "9999:9999/udp"
    volumes:
      - ./config:/opt/kong

  hello-service:
    build: ./hello-service
    restart: always
    hostname: hello-service
    ports:
      - 4000:4000

  user-service:
    build: ./user-service
    restart: always
    hostname: user-service
    ports:
      - 4001:4001
    