_format_version: "2.1"
_transform: true

services:
- url: http://hello-service:4000
  name: hello-service
  protocol: http
  routes:
  - name: hello-route
    paths:
    - /hello
    strip_path: true
- url: http://user-service:4001
  name: user-service
  protocol: http
  routes:
  - name: user-route
    paths:
    - /user
    strip_path: true
